# Generated by Django 4.2.16 on 2024-11-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_album_id_alter_album_album_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='order',
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
